### ISSUE TITLE
Display only one RG on hover in Bar view (stacked)

### ISSUE THREAD

**Issue by martinhesdahl** [keesschollaart81/AzureCostInsights.Marketplace#11]
We have around 20 RG's showing in the Azure Cost Bar (stacked) view. When I hover over one day I see a summary of the entire day. But I would like to see only the RG that I'm hovering over. A configuration boolean to be able to do this is also possible.

Gr Martin

**Comment by keesschollaart81** [comment]
Would it also be OK if the make the hover-ed RG bold/underlined? (since I expect/assume that >20 labels will be an edge case)

**Comment by martinhesdahl** [comment]
Yes that would be a great improvement!

**Comment by keesschollaart81** [comment]
Ok, for release 1.5 I've solved it a bit differently. ChartJs has a couple of '[tooltip-interactions](https://www.chartjs.org/samples/latest/tooltips/interactions.html)', depending on the number of labels and the height of the widget is switch between 'index' and 'point'. Index if the number of values is low and there is enough space in the widget, otherwise point. This is basically the solution you proposed! :-)

**Comment by keesschollaart81** [comment]
Now available with release v1.5.0
