### ISSUE TITLE
Download Cost Data not Working

### ISSUE THREAD

**Issue by srike4** [keesschollaart81/AzureCostInsights.Marketplace#26]
Hi Kees,

Getting the below error while downloading the cost data from azure portal.
Can you please help here?

Downloading costs using Usage API
Unhandled exception during Download Task { Error: Error SyntaxError: Unexpected token ﻿ in JSON at position 0 occurred in deserializing the responseBody - ﻿{"OfferTerms":[],"Meters":[{"EffectiveDate":"2019-10-28T00:00:00Z","IncludedQu

**Comment by AUGuru** [comment]
Same, has been occurring since about 12/19/19. We use this on a dashboard and I'm trying to talk the powers that be to buying a license so I can monitor multiple subscriptions for executives to see our daily azure costs, and our DevOps efforts to reduce those, so getting it working again would be excellent!

**Comment by keesschollaart81** [comment]
Yes, sorry, back from holidays! Will look into it this week! Sorry for the inconvenience!

**Comment by keesschollaart81** [comment]
It seems there has been a change to the RateCard api that breaks the Commerce JS SDK. I've created an issue here:

https://github.com/Azure/azure-sdk-for-js/issues/6780

I'll wait a bit to see what they think as I dont really have a workaround?

**Comment by keesschollaart81** [comment]
It was a bug in the Azure Rate Cart REST API which is now fixed (as it seems). Please reopen if you still face this issue!
